# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MBProgressHUD网络加载视图' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MBProgressHUD网络加载视图

pod ‘MBProgressHUD’
end
